Make usage prints nice & colorful.

diff --git a/p4-annotate b/p4-annotate
--- a/p4-annotate
+++ b/p4-annotate
@@ -6,12 +6,13 @@
 
 set -e
 
+source "p4-help-functions"
+
 if [[ $# -ne 2 ]]; then
+    echo "${RED}Missing arguments.${NO_COLOR}" >&2
     echo "usage: $(basename $0) file line" >&2
     exit 1
 fi
-
-source p4-help-functions
 
 FILE="$1"
 LINE="$2"
diff --git a/p4-delete-changelist b/p4-delete-changelist
--- a/p4-delete-changelist
+++ b/p4-delete-changelist
@@ -8,17 +8,28 @@
 
 set -e
 
-source "p4-help-functions" || true
+source "p4-help-functions"
 
-if [[ $# -lt 1 ]]; then
-    echo "usage: $(basename $0) changelist[s]" >&2
-    echo "Description: removes shelve, reverts files and finally deletes changelist." >&2
-    exit 1
+usage() {
+    echo "$(basename $0) -- removes shelve, reverts files and finally deletes changelist." >&2
+    echo "usage: $(basename $0) [options] changelist[s]" >&2
+    echo "  -f   force delete (don't as questions)" >&2
+}
+
+if [[ "$1" == "-h" ]]; then
+    usage
+    exit 0
 fi
 
 if [[ "$1" == "-f" ]]; then
     FORCE=1
     shift
+fi
+
+if [[ $# -lt 1 ]]; then
+    echo "${RED}Missing changelist[s] arguments.${NO_COLOR}" >&2
+    usage
+    exit 1
 fi
 
 for CHANGELIST in "$@"; do
diff --git a/p4-delete-client b/p4-delete-client
--- a/p4-delete-client
+++ b/p4-delete-client
@@ -24,6 +24,8 @@ if [[ "${CLIENT_NAME}" != "${HOSTNAME}" ]]; then
     CLIENT_PATH=$(p4-client-path)   # sourced in p4-help-functions
 fi
 
+echo -en "${RED}"
+
 while getopts "h?fc:n" opt; do
     case "${opt}" in
         h)
@@ -38,10 +40,8 @@ while getopts "h?fc:n" opt; do
             CLIENT_FULL_STRING=$(p4 clients -u $USER | grep "${CLIENT_NAME}")
             CLIENT_NAME=$(echo ${CLIENT_FULL_STRING} | awk '{print $2}')
             if [[ -z "${CLIENT_NAME}" ]]; then
-                echo -en "${RED}" >&2
-                echo "Couldn't find client: ${CLIENT_NAME}" >&2
-                echo "Or client doesn't belong to you ($USER)" >&2
-                echo -en "${NO_COLOR}" >&2
+                echo -e "${RED}Couldn't find client: ${CLIENT_NAME}" >&2
+                echo -e "Or client doesn't belong to you ($USER)${NO_COLOR}" >&2
                 usage
                 exit 3
             fi
@@ -61,6 +61,8 @@ while getopts "h?fc:n" opt; do
     esac
 done
 shift $(( OPTIND - 1 ))
+
+echo -en "${NO_COLOR}"
 
 if [[ -n "$1" ]]; then # there shouldn't be anymore arguments
     echo -e "${RED}Illegal argument.${NO_COLOR}" >&2
