Making -h option respond faster
By not needing to run p4 commands before arguments are parsed

diff --git a/p4-delete-client b/p4-delete-client
--- a/p4-delete-client
+++ b/p4-delete-client
@@ -18,13 +18,7 @@ usage() {
     echo    "  -n         don't delete files" >&2
 }
 
-CLIENT_NAME=$(p4-client-name)   # sourced in p4-help-functions
-if [[ "${CLIENT_NAME}" != "${HOSTNAME}" ]]; then
-    # perforce returns the hostname when not in a p4 client dir
-    CLIENT_PATH=$(p4-client-path)   # sourced in p4-help-functions
-fi
-
-echo -en "${RED}"
+echo -en "${RED}" >&2
 
 while getopts "h?fc:n" opt; do
     case "${opt}" in
@@ -43,13 +37,9 @@ while getopts "h?fc:n" opt; do
                 echo -e "${RED}Couldn't find client: ${CLIENT_NAME}" >&2
                 echo -e "Or client doesn't belong to you ($USER)${NO_COLOR}" >&2
                 usage
-                exit 3
+                exit 2
             fi
             CLIENT_PATH=$(echo ${CLIENT_FULL_STRING} | awk '{print $5}')
-            if [[ ! -d "${CLIENT_PATH}" ]]; then
-                # nothing to delete
-                CLIENT_PATH=
-            fi
             ;;
         n)
             NO_FILES=1
@@ -62,26 +52,29 @@ while getopts "h?fc:n" opt; do
 done
 shift $(( OPTIND - 1 ))
 
-echo -en "${NO_COLOR}"
+echo -en "${NO_COLOR}" >&2
 
 if [[ -n "$1" ]]; then # there shouldn't be anymore arguments
-    echo -e "${RED}Illegal argument.${NO_COLOR}" >&2
+    echo -e "${RED}Illegal argument/s - $@${NO_COLOR}" >&2
     usage
-    exit 4
+    exit 3
 fi
 
-if [[ -n "${NO_FILES}" ]]; then
-    CLIENT_PATH=
+if [[ -z $CLIENT_NAME ]]; then
+    CLIENT_NAME=$(p4-client-name)   # sourced in p4-help-functions
+    CLIENT_PATH=$(p4-client-path)   # sourced in p4-help-functions
 fi
 
 if [[ "${CLIENT_NAME}" == "${HOSTNAME}" ]]; then
     # perforce returns the hostname when not in a p4 client dir
-    echo -en "${RED}" >&2
-    echo "Not inside a p4 client directory - can't determine current client." >&2
-    echo "Move to a p4 client directory or use the -c option." >&2
-    echo -en "${NO_COLOR}" >&2
+    echo -e "${RED}Not inside a p4 client directory - can't determine current client." >&2
+    echo -e "Move to a p4 client directory or use the -c option.${NO_COLOR}" >&2
     usage
-    exit 2
+    exit 4
+fi
+
+if [[ -n "${NO_FILES}" || ! -d "${CLIENT_PATH}" ]]; then
+    CLIENT_PATH=
 fi
 
 changelists=$(p4 changes -s pending -u $USER -c "${CLIENT_NAME}")   # split inorder to catch a login error.
@@ -100,7 +93,7 @@ if [[ -z "${FORCE}" ]]; then
         exit 0
     fi
 fi
-echo >&2
+echo
 
 default_changelist_files=$(p4 opened -C "${CLIENT_NAME}" 2> /dev/null | grep "${P4_DEFAULT_CHANGE}" | sed "s/#.*//g")
 if [[ -n "${changelists}" ]] || [[ -n "${default_changelist_files}" ]]; then
@@ -128,11 +121,10 @@ if [[ -n "${changelists}" ]] || [[ -n "${default_changelist_files}" ]]; then
         p4-fix-hostname "${CLIENT_NAME}" "${FORCE}"   # sourced in p4-help-functions
         p4 -c ${CLIENT_NAME} revert ${default_changelist_files}
     fi
-    echo >&2
+    echo
 fi
 
 # unlocking p4 client using p4 client stdin & stdout option.
-# sed will change locked to unlocked only in the Options line.
 p4 client -o "${CLIENT_NAME}" | sed '/^Options:/ s= locked = unlocked =' | p4 client -i > /dev/null
 
 # delete the client now when it's unlocked
@@ -143,8 +135,8 @@ if [[ -n "${CLIENT_PATH}" ]]; then
     echo -n "Deleting files... "
     rm -rf "${CLIENT_PATH}"
     echo "Done!"
-    echo
-    echo "  cd $(echo ${CLIENT_PATH} | sed 's/\(.*\)\/.*/\1/')" # omit last directory
+    echo >&2
+    echo "  cd $(echo ${CLIENT_PATH} | sed 's/\(.*\)\/.*/\1/')" >&2 # omit last directory
     echo >&2
     echo -e "${CYAN}There is no spoon.${NO_COLOR} (${CLIENT_PATH} is now gone)." >&2
 fi
